/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

import org.junit.Assert;
import org.junit.Test;

public class BinarySearchTreeTest {
	@Test
	public void WhenNmbersAreAddedToBinarySearchTreeShouldReturnSize() {
		BinarySearchTree<Integer> binaryTree = new BinarySearchTree<>();
		binaryTree.add(56);
		binaryTree.add(30);
		// binaryTree.add(70);
		Assert.assertEquals(3, binaryTree.getSize());
	}
}
